---
title       : Washington State K-12 Enrollment
subtitle    : A visual comparison by county and school district, 2012-2013
author      : k12eddata
job         : Johns Hopkins University, "Developing Data Products"
logo        : wamap2small.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---   

## Why We Care about Students  

####  ![?](assets/img/question_mark.png) What is significant about Kindergarten - 12th grade (ages 5-18)?  
  
![Washington State Seal](assets/img/wasealsmall.png) The Washington State Constitution says the state has a paramount duty to educate children. [Washington Constitution, article IX, section 1](http://leg.wa.gov/Senate/Committees/WM/Documents/2014%20K12%20Citizens%20Guide.pdf) 

> "It is the paramount duty of the state to make ample provision for the education of all children residing within its borders, without distinction or preference on account of race, color, caste, or sex."  

But the Washington State Supreme Court has declared the Legislature in contempt for not fulfilling its **paramount duty** and ordered it to "purge its contempt" by the end of the 2015 session in June. [Washington Supreme Court Finds State In Contempt](http://www.courts.wa.gov/content/publicupload/eclips/2014%2009%2012%20Washington%20Supreme%20Court%20Finds%20State%20in%20Contempt%20KUOW.pdf)   

---   

## What we know  

####  ![?](assets/img/question_mark.png) How many full-time students are there?  



```
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     9.1   252.0   940.5  3399.0  3444.0 47570.0
```

   
![Student](assets/img/student_freepik.png) In 2012-2013 there were 1002848 students. They spanned 39 counties and 295 school districts.  

There was an extreme distribution of students throughout the state. The mean number of students per school district was **3399**, but the largest school district had **47570** students, and the smallest school district had **9** students.  


---   

## How this Application Helps  

####  ![?](assets/img/question_mark.png) What can this application help me understand?  

![Bar Graph](assets/img/devdataprodproject_graphsnip.png) It graphically illustrates the scope of student enrollment throughout the state. You can explore individual school district enrollment by county and compare county figures to statewide figures.  

![King Co. Enrollment Graph](assets/img/devdataprodproject_graph.png)

---   

## The Future  

####  ![?](assets/img/question_mark.png) Where is the application?   

![Student](assets/img/student_freepik.png) Visit the application site at [Washington State School District Enrollment](https://k12eddata.shinyapps.io/devdataprodproject).  


####  ![?](assets/img/question_mark.png) I want to learn more. Where do I start?  

![Washington State OSPI](assets/img/waospiseal.png) Visit the [Office of Superintendent of Public Instruction](http://www.k12.wa.us). This state office is the custodian of enrollment and financial information for K-12 education.  
  
##### Thank you for your interest in our children's future!   

All images are the property of the original owner. These images are used only for educational purposes.  
